// <auto-generated />
using System;
using AccountingPro.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AccountingPro.Infrastructure.Migrations
{
    [DbContext(typeof(AccountingDbContext))]
    [Migration("20251007161326_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AccountingPro.Core.Entities.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountType")
                        .HasColumnType("int");

                    b.Property<decimal>("Balance")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("ParentAccountId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ParentAccountId");

                    b.HasIndex("CompanyId", "Code")
                        .IsUnique();

                    b.ToTable("Accounts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccountType = 1,
                            Balance = 0m,
                            Code = "1000",
                            CompanyId = 1,
                            CreatedAt = new DateTime(2025, 10, 7, 16, 13, 26, 241, DateTimeKind.Utc).AddTicks(8879),
                            CreatedBy = "System",
                            Description = "Cash and cash equivalents",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Cash"
                        },
                        new
                        {
                            Id = 2,
                            AccountType = 1,
                            Balance = 0m,
                            Code = "1100",
                            CompanyId = 1,
                            CreatedAt = new DateTime(2025, 10, 7, 16, 13, 26, 241, DateTimeKind.Utc).AddTicks(8882),
                            CreatedBy = "System",
                            Description = "Money owed by customers",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Accounts Receivable"
                        },
                        new
                        {
                            Id = 3,
                            AccountType = 1,
                            Balance = 0m,
                            Code = "1200",
                            CompanyId = 1,
                            CreatedAt = new DateTime(2025, 10, 7, 16, 13, 26, 241, DateTimeKind.Utc).AddTicks(8885),
                            CreatedBy = "System",
                            Description = "Goods for sale",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Inventory"
                        },
                        new
                        {
                            Id = 4,
                            AccountType = 2,
                            Balance = 0m,
                            Code = "2000",
                            CompanyId = 1,
                            CreatedAt = new DateTime(2025, 10, 7, 16, 13, 26, 241, DateTimeKind.Utc).AddTicks(8888),
                            CreatedBy = "System",
                            Description = "Money owed to suppliers",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Accounts Payable"
                        },
                        new
                        {
                            Id = 5,
                            AccountType = 2,
                            Balance = 0m,
                            Code = "2100",
                            CompanyId = 1,
                            CreatedAt = new DateTime(2025, 10, 7, 16, 13, 26, 241, DateTimeKind.Utc).AddTicks(8890),
                            CreatedBy = "System",
                            Description = "Long-term debt",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Bank Loan"
                        },
                        new
                        {
                            Id = 6,
                            AccountType = 3,
                            Balance = 0m,
                            Code = "3000",
                            CompanyId = 1,
                            CreatedAt = new DateTime(2025, 10, 7, 16, 13, 26, 241, DateTimeKind.Utc).AddTicks(8893),
                            CreatedBy = "System",
                            Description = "Owner's investment in business",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Owner's Equity"
                        },
                        new
                        {
                            Id = 7,
                            AccountType = 4,
                            Balance = 0m,
                            Code = "4000",
                            CompanyId = 1,
                            CreatedAt = new DateTime(2025, 10, 7, 16, 13, 26, 241, DateTimeKind.Utc).AddTicks(8895),
                            CreatedBy = "System",
                            Description = "Income from sales",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Sales Revenue"
                        },
                        new
                        {
                            Id = 8,
                            AccountType = 5,
                            Balance = 0m,
                            Code = "5000",
                            CompanyId = 1,
                            CreatedAt = new DateTime(2025, 10, 7, 16, 13, 26, 241, DateTimeKind.Utc).AddTicks(8898),
                            CreatedBy = "System",
                            Description = "Direct costs of production",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Cost of Goods Sold"
                        },
                        new
                        {
                            Id = 9,
                            AccountType = 5,
                            Balance = 0m,
                            Code = "5100",
                            CompanyId = 1,
                            CreatedAt = new DateTime(2025, 10, 7, 16, 13, 26, 241, DateTimeKind.Utc).AddTicks(8900),
                            CreatedBy = "System",
                            Description = "Office rent",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Rent Expense"
                        },
                        new
                        {
                            Id = 10,
                            AccountType = 5,
                            Balance = 0m,
                            Code = "5200",
                            CompanyId = 1,
                            CreatedAt = new DateTime(2025, 10, 7, 16, 13, 26, 241, DateTimeKind.Utc).AddTicks(8903),
                            CreatedBy = "System",
                            Description = "Electricity, water, etc.",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Utilities Expense"
                        });
                });

            modelBuilder.Entity("AccountingPro.Core.Entities.AccountingPeriod", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("FiscalYearId")
                        .HasColumnType("int");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("FiscalYearId");

                    b.ToTable("AccountingPeriods");
                });

            modelBuilder.Entity("AccountingPro.Core.Entities.Company", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("TaxId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.ToTable("Companies");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "123 Business Street, City, State 12345",
                            Code = "SAMPLE",
                            CreatedAt = new DateTime(2025, 10, 7, 16, 13, 26, 241, DateTimeKind.Utc).AddTicks(8766),
                            CreatedBy = "System",
                            Email = "info@samplecompany.com",
                            IsActive = true,
                            IsDeleted = false,
                            Name = "Sample Company Ltd.",
                            Phone = "+1-555-0123",
                            TaxId = "12-3456789"
                        });
                });

            modelBuilder.Entity("AccountingPro.Core.Entities.FiscalYear", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId", "Year")
                        .IsUnique();

                    b.ToTable("FiscalYears");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompanyId = 1,
                            CreatedAt = new DateTime(2025, 10, 7, 16, 13, 26, 241, DateTimeKind.Utc).AddTicks(8950),
                            CreatedBy = "System",
                            EndDate = new DateTime(2024, 12, 31, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            IsCurrent = true,
                            IsDeleted = false,
                            StartDate = new DateTime(2024, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Status = 1,
                            Year = 2024
                        });
                });

            modelBuilder.Entity("AccountingPro.Core.Entities.JournalEntry", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ApprovedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("ApprovedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime>("EntryDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("EntryNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsReversed")
                        .HasColumnType("bit");

                    b.Property<string>("Reference")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<int?>("ReversalOfEntryId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.Property<decimal>("TotalCredit")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("TotalDebit")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ReversalOfEntryId");

                    b.HasIndex("CompanyId", "EntryNumber")
                        .IsUnique();

                    b.ToTable("JournalEntries");
                });

            modelBuilder.Entity("AccountingPro.Core.Entities.JournalEntryLine", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("AccountId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("CreditAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("DebitAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("JournalEntryId")
                        .HasColumnType("int");

                    b.Property<int>("TransactionType")
                        .HasColumnType("int");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.HasIndex("JournalEntryId");

                    b.ToTable("JournalEntryLines");
                });

            modelBuilder.Entity("AccountingPro.Core.Entities.Account", b =>
                {
                    b.HasOne("AccountingPro.Core.Entities.Company", "Company")
                        .WithMany("Accounts")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AccountingPro.Core.Entities.Account", "ParentAccount")
                        .WithMany("ChildAccounts")
                        .HasForeignKey("ParentAccountId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Company");

                    b.Navigation("ParentAccount");
                });

            modelBuilder.Entity("AccountingPro.Core.Entities.AccountingPeriod", b =>
                {
                    b.HasOne("AccountingPro.Core.Entities.FiscalYear", "FiscalYear")
                        .WithMany("AccountingPeriods")
                        .HasForeignKey("FiscalYearId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FiscalYear");
                });

            modelBuilder.Entity("AccountingPro.Core.Entities.FiscalYear", b =>
                {
                    b.HasOne("AccountingPro.Core.Entities.Company", "Company")
                        .WithMany("FiscalYears")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Company");
                });

            modelBuilder.Entity("AccountingPro.Core.Entities.JournalEntry", b =>
                {
                    b.HasOne("AccountingPro.Core.Entities.Company", "Company")
                        .WithMany("JournalEntries")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AccountingPro.Core.Entities.JournalEntry", "ReversalOfEntry")
                        .WithMany()
                        .HasForeignKey("ReversalOfEntryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Company");

                    b.Navigation("ReversalOfEntry");
                });

            modelBuilder.Entity("AccountingPro.Core.Entities.JournalEntryLine", b =>
                {
                    b.HasOne("AccountingPro.Core.Entities.Account", "Account")
                        .WithMany("JournalEntryLines")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("AccountingPro.Core.Entities.JournalEntry", "JournalEntry")
                        .WithMany("JournalEntryLines")
                        .HasForeignKey("JournalEntryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");

                    b.Navigation("JournalEntry");
                });

            modelBuilder.Entity("AccountingPro.Core.Entities.Account", b =>
                {
                    b.Navigation("ChildAccounts");

                    b.Navigation("JournalEntryLines");
                });

            modelBuilder.Entity("AccountingPro.Core.Entities.Company", b =>
                {
                    b.Navigation("Accounts");

                    b.Navigation("FiscalYears");

                    b.Navigation("JournalEntries");
                });

            modelBuilder.Entity("AccountingPro.Core.Entities.FiscalYear", b =>
                {
                    b.Navigation("AccountingPeriods");
                });

            modelBuilder.Entity("AccountingPro.Core.Entities.JournalEntry", b =>
                {
                    b.Navigation("JournalEntryLines");
                });
#pragma warning restore 612, 618
        }
    }
}
